int
_esymtab_search_(), 
arpwhohas(), 
cfg_number(), 
config_scan(), 
ether_input(), 
ether_output(), 
ether_sprintf(), 
if_attach(), 
kmem_phys(), 
log(), 
loops_per_usec(), 
m_adj(), 
m_clalloc(), 
m_copydata(), 
m_freem(), 
m_retry(), 
m_retryhdr(), 
malloc(), 
mbstat(), 
mbtypes(), 
mbutl(), 
mclfree(), 
mclrefcnt(), 
netmask(), 
new_isa_configure(), 
printf(), 
splimp(), 
splx(); 

const struct tbl {
	const char *name;
	int (*func)();
} kernpermsym[] = {
"_esymtab_search_1",	_esymtab_search_,
"arpwhohas1",	arpwhohas,
"cfg_number1",	cfg_number,
"config_scan1",	config_scan,
"ether_input1",	ether_input,
"ether_output1",	ether_output,
"ether_sprintf1",	ether_sprintf,
"if_attach1",	if_attach,
"kmem_phys1",	kmem_phys,
"log1",	log,
"loops_per_usec1",	loops_per_usec,
"m_adj1",	m_adj,
"m_clalloc1",	m_clalloc,
"m_copydata1",	m_copydata,
"m_freem1",	m_freem,
"m_retry1",	m_retry,
"m_retryhdr1",	m_retryhdr,
"malloc1",	malloc,
"mbstat1",	mbstat,
"mbtypes1",	mbtypes,
"mbutl1",	mbutl,
"mclfree1",	mclfree,
"mclrefcnt1",	mclrefcnt,
"netmask1",	netmask,
"new_isa_configure1",	new_isa_configure,
"printf1",	printf,
"splimp1",	splimp,
"splx1",	splx,
0
};
