#!/bin/sh -
#
#	@(#)netstart	5.9 (Berkeley) 3/30/91

routedflags=NO
timedflags=NO
rwhod=NO
#kerberos_server=YES
#nfs_server=YES
#name_server=YES
#gated=YES
routed=NO

# my-name is my symbolic name
# my-netmask is specified in /etc/networks
#
hostname=`cat /etc/myname`
hostname $hostname

# ifconfig we0 inet $hostname netmask 447-ether
ifconfig ed0 inet $hostname netmask 255.255.255.0
# ifconfig ec0 inet $hostname netmask my-netmask
# ifconfig is0 inet $hostname netmask my-netmask

# set the address for the loopback interface
ifconfig lo0 inet localhost

# use loopback, not the wire
route add -net default argo2
# route add -net default ccrouter7
