.\" Copyright (c) 1994 William F. Jolitz, TeleMuse
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This software is a component of "386BSD" developed by 
.\"	William F. Jolitz, TeleMuse.
.\" 4. Neither the name of the developer nor the name "386BSD"
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\" 5. Non-commercial distribution of this complete file in either source and/or
.\"    binary form at no charge to the user (such as from an official Internet 
.\"    archive site) is permitted. 
.\" 6. Commercial distribution and sale of this complete file in either source
.\"    and/or binary form on any media, including that of floppies, tape, or 
.\"    CD-ROM, or through a per-charge download such as that of a BBS, is not 
.\"    permitted without specific prior written permission.
.\" 7. Non-commercial and/or commercial distribution of an incomplete, altered, 
.\"    or otherwise modified file in either source and/or binary form is not 
.\"    permitted.
.\"
.\" THIS SOFTWARE IS A COMPONENT OF 386BSD DEVELOPED BY WILLIAM F. JOLITZ 
.\" AND IS INTENDED FOR RESEARCH AND EDUCATIONAL PURPOSES ONLY. THIS 
.\" SOFTWARE SHOULD NOT BE CONSIDERED TO BE A COMMERCIAL PRODUCT. 
.\" THE DEVELOPER URGES THAT USERS WHO REQUIRE A COMMERCIAL PRODUCT 
.\" NOT MAKE USE OF THIS WORK.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE DEVELOPER ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE DEVELOPER BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $Id: malloc.9,v 1.1 94/10/20 00:03:03 bill Exp $
.\"
.Dd August 29, 1994
.Dt MALLOC 9
.Os 386BSD 1
.Sh NAME
.Nm malloc
.Nd kernel dynamic memory allocator
.Sh SYNOPSIS
.Fd #include """malloc.h"""
.Ft "void *"
.Fn malloc "u_long size" "int type" "int flags"
.Ft void
.Fn free "void *addr" "int type"
.Sh DESCRIPTION
Most shared resources in the 386BSD kernel are dynamically allocated on
demand to serve need (with administrative bounds present to avoid system
overrun). The
.Fn malloc
function is used to allocate small (<= 64KB) portions of memory in the kernel,
and is especially useful in sub-page sized allocations, since it maintains a
free pool of page fragments to allocate from.
.Pp
While this function superfically resembles the user mode
.Xr malloc 3
function, it has two additional arguments.
Associated with each allocation is a
.Fa type
which tags allocations of a given kind for use in statistics and run-away
allocation prevention. In addition,
.Fn malloc
has a
.Fa flags
argument to select optional handling (M_NOWAIT is the most common option,
allowing the function to be used from interrupt level by disallowing a
block if no space available).
.Pp
The
.Fn malloc
function obtains memory for its pool from the virtual memory system via
the 
.Xr kmem 9
facility.
.Pp
The
.Fn free
function returns used memory to the memory pool. If a surplus of memory
is present in the allocator's pool, it will attempt to return whole pages
back to the
.Xr kmem 9
facility. As such, it defers to the virtual memory system as the primary
location where memory resource resides.
.Pp
Since the virtual memory system itself makes use of
.Fn malloc
for its operation, care is taken to avoid recursion.
.Pp
.Sh RETURN VALUES
The
.Fn malloc
function returns
a address of the allocated resource if successful; otherwise
a null address is returned.
.Sh SEE ALSO
.Xr kmem 9
