int
_esymtab_search_(), 
/* arpwhohas(),  */
cfg_number(), 
config_scan(), 
ether_input(), 
ether_output(), 
ether_sprintf(), 
if_attach(), 
kmem_phys(), 
log(), 
loops_per_usec(), 
m_adj(), 
m_clalloc(), 
m_copydata(), 
m_freem(), 
m_retry(), 
m_retryhdr(), 
malloc(), 
mbstat(), 
mbtypes(), 
mbutl(), 
mclfree(), 
mclrefcnt(), 
netmask(), 
new_isa_configure(), 
printf(), 
splimp(), 
splx(), 
zero(); 

const struct tbl {
	const char *name;
	int (*func)();
} kernpermsym[] = {
"__esymtab_search_",	_esymtab_search_,
/* "_arpwhohas",	arpwhohas, */
"_cfg_number",	cfg_number,
"_config_scan",	config_scan,
"_ether_input",	ether_input,
"_ether_output",	ether_output,
"_ether_sprintf",	ether_sprintf,
"_if_attach",	if_attach,
"_kmem_phys",	kmem_phys,
"_log",	log,
"_loops_per_usec",	loops_per_usec,
"_m_adj",	m_adj,
"_m_clalloc",	m_clalloc,
"_m_copydata",	m_copydata,
"_m_freem",	m_freem,
"_m_retry",	m_retry,
"_m_retryhdr",	m_retryhdr,
"_malloc",	malloc,
"_mbstat",	mbstat,
"_mbtypes",	mbtypes,
"_mbutl",	mbutl,
"_mclfree",	mclfree,
"_mclrefcnt",	mclrefcnt,
"_netmask",	netmask,
"_new_isa_configure",	new_isa_configure,
"_printf",	printf,
"_splimp",	splimp,
"_splx",	splx,
"_zero",	zero,
0
};
