# $Id: $
#
# GNU program stuff
#

# Things to use in general

CFLAGS += -DSTDC_HEADERS
NONSTDINC=$(INCOLDBSD)

# Things we have.

CFLAGS += \
	-DHAVE_GETPAGESIZE -DHAVE_UNISTD_H -DHAVE_SYS_PARAM_H \
	-DHAVE_STRERROR -DHAVE_MEMCHR  -DHAVE_MEMCPY \
	-DHAVE_LIMITS_H  -DHAVE_SYS_MTIO_H -DHAVE_STRSTR \
	-DHAVE_MKDIR -DHAVE_MKNOD -DHAVE_RENAME -DHAVE_GETCWD \
	-DHAVE_FTRUNCATE -DHAVE_GETPWUID -DHAVE_GETGRGID
#	-DHAVE_WORKING_MMAP

# Things we need.

# CFLAGS += -DNEED_

# Libraries:

