#!/bin/sh -
#
#	@(#)netstart	5.9 (Berkeley) 3/30/91

routedflags=NO
timedflags=NO
rwhod=NO
#kerberos_server=YES
#nfs_server=YES
#name_server=YES
#gated=YES
routed=NO

hostname=`cat /etc/myname`
hostname $hostname

#
# my-netmask is specified in /etc/networks
#

# ifconfig we0 inet $hostname netmask my-netmask
# ifconfig ed0 inet $hostname netmask my-netmask
# ifconfig ec0 inet $hostname netmask my-netmask
# ifconfig is0 inet $hostname netmask my-netmask

# set the address for the loopback interface
ifconfig lo0 inet localhost

# use loopback, not the wire
route add $hostname localhost
