#	@(#)Makefile	5.8.1.1 (Berkeley) 5/8/91

SUBDIR=	ar at awk bc biff basename cal calendar \
	checknr chpass cksum cmp col colcrt colrm column comm compress \
	cpio crontab ctags cut dc diff diff3 dirname du elvis elvisrecover \
	env expand false file find finger fmt fold from fstat ftp \
	gas gcc gdb gprof grep groups head hexdump id join \
	ktrace last ld leave lex locate lock logger \
	login logname lorder m4 machine mail make man mesg mkdep mkfifo \
	mkstr more netstat nfsstat nice nm nohup pagesize \
	passwd paste pr printenv printf ranlib rcs \
	rdist renice rlogin rsh script sed \
	shar showmount size soelim sort split strings \
	strip su symorder tail talk tar tee telnet tftp time \
	tip tn3270 touch tput tr true tset tsort tty ul unexpand unifdef uniq \
	unvis users uudecode uuencode vacation vis vmstat \
	w wall wc what whereis which who whoami whois \
	write xargs xinstall xstr yacc yes

# notyet: g++ groff nvi
.include <bsd.subdir.mk>
