# notyet SUBDIR=	 `ls [a-z]*`

SUBDIR=	 \
ar at awk basename bc biff cal calendar checknr chpass cksum cmp col colcrt colrm column \
comm compress cpio crontab ctags cut dc diff diff3 dirname du elvis elvisrecover env error \
expand false file find finger fmt fold fpr from fsplit fstat ftp gas gcc gdb getopt \
gprof grep groups head hexdump id indent join ktrace last ld leave lex locate lock \
logger login logname look lorder m4 machine mail make man mesg mkdep mkfifo mkstr more \
netstat nfsstat nice nm nohup pagesize passwd paste pr printenv printf ranlib rcs rdist \
renice rlogin rpcinfo rsh script sed shar showmount size soelim sort split strings strip \
su symorder tail talk tar tee telnet tftp time tip tn3270 touch tput tr true tset tsort \
tty ul unexpand unifdef uniq unvis users uudecode uuencode vacation vgrind vis vmstat w \
wall wc what whereis which who whoami whois window write xargs xinstall xstr  yacc yes


# notyet: g++ groff nvi
.include <bsd.subdir.mk>
