.TH HOSTNAME 1L "GNU Shell Utilities" "FSF" \" -*- nroff -*-
.SH NAME
hostname \- set or print the name of the current host system
.SH SYNOPSIS
.B hostname [name]
.br
.B hostname
{\-\-help,\-\-version}
.SH DESCRIPTION
This manual page
documents the GNU version of
.BR hostname .
With no arguments,
.B hostname
prints the name of the current host system.
With one argument, it sets the current host name to the specified string.
Usually, only a privileged user may set the host name.
.SS OPTIONS
.TP
.I "\-\-help"
Print a usage message on standard output and exit successfully.
.TP
.I "\-\-version"
Print version information on standard output then exit successfully.
