.if n \{\
.	ds ct "
.\}
.if t \{\
.	ds ct \\(co
.\}
.TH MESSAGES 1L "Elm Version 2.4" "USENET Community Trust"
.SH NAME
messages - quick count of messages in mailbox or folder
.SH SYNOPSIS
.B messages
.br
.B messages
folder-name
.SH DESCRIPTION
.I Messages
counts the occurrences of "^From\ " in either the current incoming 
mailbox or the specified folder.
.P
This is, in fact, a simple little shell script!!
.SH AUTHOR
Elm Development Group
.SH SEE ALSO
from(1L), elm(1L)
.SH BUGS
Don't be foolish...
.SH BUG REPORTS TO
Syd Weinstein	elm@DSI.COM	(dsinc!elm)
.SH COPYRIGHTS
\fB\*(ct\fRCopyright 1988-1992 by The USENET Community Trust
.br
Derived from Elm 2.0, \fB\*(ct\fR Copyright 1986, 1987 by Dave Taylor
