.TH WHOAMI 1L "GNU Shell Utilities" "FSF" \" -*- nroff -*-
.SH NAME
whoami \- print effective userid
.SH SYNOPSIS
.B whoami [\-\-help] [\-\-version]
.SH DESCRIPTION
This manual page
documents the GNU version of
.BR whoami .
.B whoami
prints the user name associated with the current effective user ID.
It is equivalent to the command `id \-un'.
.SS OPTIONS
.TP
.I "\-\-help"
Print a usage message on standard output and exit successfully.
.TP
.I "\-\-version"
Print version information on standard output then exit successfully.
