#!/bin/sh
# $XConsortium: xinitrc.cpp,v 1.4 91/08/22 11:41:34 rws Exp $

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/usr/X386/lib/X11/xinit/.Xresources
sysmodmap=/usr/X386/lib/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f $userresources ]; then
    xrdb -merge $userresources
fi

if [ -f $usermodmap ]; then
    xmodmap $usermodmap
fi

# start some nice programs

twm &
xclock -geometry 50x50-1+1 &
#xterm -geometry 80x30+494+51 &
#xterm -geometry 80x20+494-0 &
xterm -geometry 80x30-1-1 &
xterm -geometry 80x20+300-1 &
exec xterm -C -geometry 80x25+0+0 -name login
